/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ostteam_audiorecorder_Core */

#ifndef _Included_org_ostteam_audiorecorder_Core
#define _Included_org_ostteam_audiorecorder_Core
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_engineInit(JNIEnv *jEnv, jobject jObj);

JNIEXPORT void JNICALL Java_org_ostteam_audiorecorder_Core_engineRelease(JNIEnv *jEnv, jobject jObj);

JNIEXPORT void JNICALL Java_org_ostteam_audiorecorder_Core_tick(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_start(JNIEnv *jEnv, jobject jObj, jstring jWavFilepath, jint buffersPerSec, jboolean keepAvgsOfSamples);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_pause(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_resume(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_stop(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_reset(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_isActive(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_isRecording(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_isPaused(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jlong JNICALL Java_org_ostteam_audiorecorder_Core_samplesCount(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jlong JNICALL Java_org_ostteam_audiorecorder_Core_samplesBytes(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jfloat JNICALL Java_org_ostteam_audiorecorder_Core_samplesSecs(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jfloat JNICALL Java_org_ostteam_audiorecorder_Core_samplesRelAvg(JNIEnv *jEnv, jobject jObj, jboolean resetAvg);

//player

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_playerLoad(JNIEnv *jEnv, jobject jObj, jstring jFilepath, jint buffersPerSec);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_playerPlay(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_playerPause(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_playerStop(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_playerIsLoaded(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_playerIsPaused(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_playerSeekRelPos(JNIEnv *jEnv, jobject jObj, jfloat relPos);

JNIEXPORT jfloat JNICALL Java_org_ostteam_audiorecorder_Core_playerRelProgress(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jfloat JNICALL Java_org_ostteam_audiorecorder_Core_playerSecsTotal(JNIEnv *jEnv, jobject jObj);

//encoder

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_encoderStart(JNIEnv *jEnv, jobject jObj, jstring jFilepathIn, jstring jFilepathOut, jstring jFormatId);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_encoderIsLoaded(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jfloat JNICALL Java_org_ostteam_audiorecorder_Core_encoderRelProgress(JNIEnv *jEnv, jobject jObj);

JNIEXPORT jboolean JNICALL Java_org_ostteam_audiorecorder_Core_encoderFinish(JNIEnv *jEnv, jobject jObj);

#ifdef __cplusplus
}
#endif
#endif
